// <auto-generated />
namespace MVC_Day_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MemberShipId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberShipId));
        
        string IMigrationMetadata.Id
        {
            get { return "201910040413133_MemberShipId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
