// <auto-generated />
namespace MVC_Day_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addStocks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStocks));
        
        string IMigrationMetadata.Id
        {
            get { return "201910040517479_addStocks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
